package supervisor;

public enum Subjects {
    TEMPERATURE,
    HUMIDITY,
    PRESSURE,
    AIR_QUALITY,
    UV_INDEX,
    LIGHT_INTENSITY,
    VOLTAGE,
    CURRENT,
    POWER_USAGE,
    FUEL_LEVEL,
    BATTERY_STATUS,
    MOTOR_SPEED,
    ENGINE_TEMPERATURE
}
